### ISSUE TITLE
ChoreonoidでOpenRTMが認識しない

### ISSUE THREAD

**Issue by anazawa-t** [OpenRTM/openrtm.github.io#1]
安藤様

お世話になっております。FSK穴澤と申します。

Ubuntu 16.04にてgithubよりOpenRTM-aistをダウンロードし、インストールを行ったのですが、Choreonoid上でOpenRTMPluginをONにするとエラーとなり、認識されません。
対応方法をご教示頂けないでしょうか。

エラー内容は下記となります。
> CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367
> (Message):
>   A required package was not found
> Call stack (most recent call first):
>   /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532
> (_pkg_check_modules_internal)
>   Src/OpenRTM/CMakeLists.txt:8 (pkg_check_modules)

以上、お手数ではございますが、宜しくお願い致します。

**Comment by Nobu19800** [comment]
産総研の宮本です。横から失礼いたします。

おそらくですが、OpenRTM-aistのインストールに失敗しています。
臨時WEBページに記載してあるコマンドの`sudo dpkg -i openrtm-aist-1.1.2-0_amd64.deb`が間違っており、正しくは`sudo dpkg -i openrtm-aist_1.1.2-0_amd64.deb`のため、もう一度コマンド入力してご確認をお願いいたします。

**Comment by anazawa-t** [comment]
宮本様

ご回答頂きありがとうございます。
無事にインストールでき、Choreonoidでも認識されるようになりました。

**Comment by n-ando** [comment]
Webページの方は修正いたしました。ご迷惑をおかけしました。
