### ISSUE TITLE
ファイル名が違う

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/openrtm.github.io#2]
C++版のインストール時に、以下のコマンドを入力するように記述がありますが、`openrtm-aist-1.1.2-0_amd64.deb`というファイルがないため失敗します。

<pre>
sudo dpkg -i openrtm-aist-1.1.2-0_amd64.deb
</pre>

正しい名前は`openrtm-aist_1.1.2-0_amd64.deb`のようです。修正をお願いいたします。

**Comment by n-ando** [comment]
修正しました。
